### ISSUE TITLE
Create a Nudget package for Pepipost C# SDK

### ISSUE THREAD

**Issue by mixerp** [pepipost/pepipost-sdk-csharp#1]
Nuget is the best way to distribute SDKs. It eases the pain of developers to download and compile the solution. Do you plan on releasing a nuget package?

**Comment by geniusdibya** [comment]
Create a Nudget for Pepipost C# SDK sp that it eases the pain of developers to download and compile the code to run for sending emails from your application.

**Comment by topdev01** [comment]
Hi, I have created and published an nuget package and can be found here:
https://www.nuget.org/packages/PepipostAPI.Standard/
